spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/lease_by
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - email
              - profile
logging:
  level:
    root: info
  file:
    name: spring-starter.log
    path: /
